feat: DWS-864 add test coverage quality gate (#20)
* feat: DWS-864 add test coverage quality gate

* feat: DWS-864 fix github var usage

---------

Co-authored-by: Александр Угловский <alex3angle@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,7 +33,21 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Run golang test
-        run: go test -v ./...
+        run: go test -v ./... -coverprofile ./coverage.out
+
+      - name: Coverage check
+        run: |
+          echo "Quality Gate: checking test coverage is above threshold"
+          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+          echo "Threshold: ${{ vars.TEST_COVERAGE_THRESHOLD }}"
+          echo "Current total coverage: $totalCoverage %"
+          if (($(echo "$totalCoverage ${{ vars.TEST_COVERAGE_THRESHOLD }}" | awk '{print ($1 >= $2)}') )); then
+            echo 'Passed'
+          else
+            echo "Current test coverage is below threshold. Please add more unit tests."
+            echo "Fail"
+            exit 1
+          fi
 
 
 
